# Site Settings
title: Saudi Holland Consultancy
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Ali Al Nassar
tagline: Consultant
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Dynamic and resourceful professional with over 16 years of experience gained through practical and challenging environments within the banking sector. Highly qualified and competent in analyzing organizational requirements and creating effective solutions resulting in maximized efficiency. Striving for excellence, aspiring to secure a position with the Saudi Dutch Company, where I can apply the diversified experience gained over the past few years supporting my children obtain their degrees within Europe and the USA. Areas of expertise include but are not limited to management, marketing, customer (student) services, and cultural diversity.'

#sidebar links
email: ali_al_naser@hotmail.com
phone: 012 345 6789
website: saudiholland.com #do not add http://
linkedin: alandoe
github: sharu725
twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
